### ISSUE TITLE
Certificate error on website

### ISSUE THREAD

**Issue by blindmanonacid** [danomatika/joyosc#12]
Hi,
I'd really like to download the release build from your website but Firefox tells me there's a security risk.

```
docs.danomatika.com uses an invalid security certificate.
 
The certificate is not trusted because it is self-signed.
 
Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT
```

This also happens on your robotcowboy.com site.

Not being sure if there's a bad actor involved or if it's just a technical problem I don't trust to visit the site. 

Thanks for looking into this if you do.

**Comment by danomatika** [comment]
There is no certificate, it’s an HTTP link. Firefox is just being picky as everyone wants HTTPS by default.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by blindmanonacid** [comment]
Thank you for the quick reply :)
