### ISSUE TITLE
OSC Quit message doesnt work with newest version.

### ISSUE THREAD

**Issue by zebra1993** [danomatika/joyosc#16]
Compiled joyosc as in issue #13 , joyosc doesn't close anymore by sending it `/joyosc/quit` via OSC. (port is default 7770)

V0.4.5 does work.

-e shows
```
joyosc: unknown message received: /joyosc/quit
joyosc: unknown message received: /joyosc/quit
joyosc: unknown message received: /joyosc/quit
joyosc: unknown message received: /joyosc/quit
```
when the message is sent a couple times

**Comment by danomatika** [comment]
There was a missing "/" in the address matching. This should be fixed by the latest commit.
