### ISSUE TITLE
joyosc on Windows

### ISSUE THREAD

**Issue by agraef** [danomatika/joyosc#18]
The program compiles fine on Windows 11 using mingw/msys2, but when I run it in the msys shell, it just locks up and never prints or outputs anything. hexler's Protokol and TouchOSC work fine there (these also use SDL) with the same controllers I have, so I believe that it might be necessary to add a main window to make the Windows version work, just like you already did for macOS.

P.S.: Dan, kudos and thanks a lot for creating this software, it's really useful for interfacing Pd with gamepads across different platforms! I'm teaching a course on sound design this semester, so I've created a little wrapper patch and a TouchOSC template which uses the same OSC messages as joyosc (see [joyosc-pd](https://github.com/agraef/joyosc-pd)), so that the students can use this on their own laptops -- we've got Linux computers in the lab, but most students have Mac or Windows. It would really be nice if we could make the Windows version work as well, so that the students could use it there in lieu of TouchOSC.

**Comment by danomatika** [comment]
Try the new -w / --window flag in 0.6.0. It should open a window on any platform.enohp ym morf tnes-----------Dan Wilcoxdanomatika.comrobotcowboy.comOn Nov 6, 2024, at 3:18 PM, Albert Graef ***@***.***> wrote:﻿
The program compiles fine on Windows 11 using mingw/msys2, but when I run it in the msys shell, it just locks up and never prints or outputs anything. hexler's Protokol and TouchOSC work fine there (these also use SDL) with the same controllers I have, so I believe that it might be necessary to add a main window to make the Windows version work, just like you already did for macOS.
P.S.: Dan, kudos and thanks a lot for creating this software, it's really useful for interfacing Pd with gamepads across different platforms! I'm teaching a course on sound design this semester, so I've created a little wrapper patch and a TouchOSC template which uses the same OSC messages as joyosc (see joyosc-pd), so that the students can use this on their own laptops -- we've got Linux computers in the lab, but most students have Mac or Windows. It would really be nice if we could make the Windows version work as well, so that the students could use it there in lieu of TouchOSC.

**Comment by agraef** [comment]
Awesome, thanks! Bug fixed even before it was reported. ;-)

Yes, I noticed that you've added that `-w` option recently, but the 0.6.0 changelog entry only mentions macOS, so I didn't understand that you had it implemented on Windows as well.

There's one little remaining issue with `-e`, though. Because the msys2 terminal uses pipes for the stdio streams, console output gets buffered in large chunks rather than being line-buffered, which is horrible for interactive usage. This is a well-known issue with mingw/msys2 console applications. It can easily be fixed, though, by flushing the ostream after printing each line. Here are the necessary diffs to cpphelpers/Log.h in case you want to tackle this:

~~~diff
diff --git a/Log.h b/Log.h
index 66e8ec2..134eead 100644
--- a/Log.h
+++ b/Log.h
@@ -59,20 +59,24 @@ class Log {
 				case LOG_LEVEL_NORMAL:
 					// must flush or we wont get any output until *after* the mainLoop
 					std::cout << m_line.str();
+					std::cout.flush();
 					break;
 
 				case LOG_LEVEL_DEBUG:
 					#ifdef DEBUG
 					std::cout << "Debug: " << m_line.str();
+					std::cout.flush();
 					#endif
 					break;
 
 				case LOG_LEVEL_WARN:
 					std::cerr << "Warn: " << m_line.str();
+					std::cerr.flush();
 					break;
 
 				case LOG_LEVEL_ERROR:
 					std::cerr << "Error: " << m_line.str();
+					std::cerr.flush();
 					break;
 			}
 		}
~~~

Yeah, I know, it's ugly, but it's the only remedy I know of. (Even that won't help in the Windows terminal where apparently a windowed application doesn't have any stdio streams at all, so nothing gets printed with `-w`. Console output on Windows is a mess, unfortunately. It's always been that way, even in the msys1 days, I've been there...)

**Comment by danomatika** [comment]
Hmm, ok. I would do this differently where a compile-time define could be set for windows only to enable flushing.

**Comment by danomatika** [comment]
I changed a few more things now so, if you can, please test with the latest master. If it's working, I will release as 0.7.0. Chnagelog is up to date for info.

**Comment by agraef** [comment]
The line buffering on Windows works now. :+1: 

Unfortunately, it looks like after the refactoring you did, the `-t` option doesn't work any more. :disappointed:

**Comment by agraef** [comment]
Here's what I get on Linux:

~~~
$ joyosc -et
listening port:  7770
listening multicast group: none
listening addr:  /joyosc
sending ip:      127.0.0.1
sending port:    8880
sending address for notifications: /joyosc/notifications
sending address for devices:       /joyosc/devices
print events?:   true
joysticks only?: false
sleep us:        10000
triggers as axes?: true
device addresses: 0
GameController: opened 0 8BitDo Pro 2 controller
  num buttons: 16
  num axes: 6
controller 8BitDo Pro 2 button: righttrigger 1
controller 8BitDo Pro 2 button: righttrigger 0
controller 8BitDo Pro 2 button: righttrigger 1
controller 8BitDo Pro 2 button: righttrigger 0
controller 8BitDo Pro 2 button: righttrigger 1
controller 8BitDo Pro 2 button: righttrigger 0
~~~

As you can see, the triggers still function as switches where they should be axis values.

**Comment by agraef** [comment]
Here's how it's supposed to look like (that's #17):

~~~
$ joyosc -et
listening port:  7770
listening multicast group: none
listening addr:  /joyosc
sending ip:      127.0.0.1
sending port:    8880
sending address for notifications: /joyosc/notifications
sending address for devices:       /joyosc/devices
print events?:   true
joysticks only?: false
sleep us:        10000
device addresses: 0
GameController: opened 0 8BitDo Pro 2 /gc0
  num buttons: 16
  num axes: 6
/gc0 8BitDo Pro 2 axis: righttrigger 3469
/gc0 8BitDo Pro 2 axis: righttrigger 4625
/gc0 8BitDo Pro 2 axis: righttrigger 6810
/gc0 8BitDo Pro 2 axis: righttrigger 9508
/gc0 8BitDo Pro 2 axis: righttrigger 14391
/gc0 8BitDo Pro 2 axis: righttrigger 22101
/gc0 8BitDo Pro 2 axis: righttrigger 28269
/gc0 8BitDo Pro 2 axis: righttrigger 32767
/gc0 8BitDo Pro 2 axis: righttrigger 26342
/gc0 8BitDo Pro 2 axis: righttrigger 9637
/gc0 8BitDo Pro 2 axis: righttrigger 0
~~~

**Comment by danomatika** [comment]
Hah, whoops. Lemme check.

**Comment by danomatika** [comment]
Ok, should be fixed in latest commits. I changed how the global option value is filtered down to the controller instances and it was only being set if there was a controller-specific tag found.

Also, feel free to forward any interesting projects using joyosc, it would be nice to see. I am also not so far from Mainz... ;)

**Comment by agraef** [comment]
Works like a charm now, **except** that the output messages suddenly look like this (output from oscparse):

~~~
joyosc devicescontroller axis righttrigger 0
~~~

I'm sure that they are supposed to look like this (which they did in the previous version, and is also what your abstractions expect):

~~~
joyosc devices axis righttrigger 0
~~~

> I am also not so far from Mainz... ;)

Awesome! I thought you were from the US. I maybe could have guessed, though, from the event pics on your project page. (I've been to the ZKM quite a few times before.)

**Comment by agraef** [comment]
> Also, feel free to forward any interesting projects using joyosc, it would be nice to see.

Well, in the sound design course we'll just use joyosc with some gamepads, nothing fancy. I'll see what the students come up with during the semester. They're still learning the ropes, though (most of them have no prior experience with computer music whatsoever). But if they come up with something interesting, I'll toss it up on github or maybe the rlp gitlab somewhere.

Myself, I've started thinking about ways to better integrate joyosc with Pd (or [purr-data](https://agraef.github.io/purr-data/), which is the Pd flavor I use in the courses). Most of my students aren't very familiar with the terminal, so it would be nice to have a little helper object which launches joyosc and redirects its terminal output to the Pd console if wanted.

**Comment by agraef** [comment]
> `joyosc devicescontroller axis righttrigger 0`

Looks wrong with the `-e` output from joyosc itself, too:

~~~
controller Microsoft Xbox Controller axis: righttrigger 0
~~~

This looks like the `m_oscAddress` address is incorrectly initialized as `"controller"` (instead of `""`) somewhere, so that the code which sets the default OSC device address at GameController.cpp:L90 is never executed. Just a guess, I'm still investigating.

**Comment by agraef** [comment]
Yeah, that was it. I fixed it like this:

~~~diff
diff --git a/src/joyosc/GameController.cpp b/src/joyosc/GameController.cpp
index 7586bb4..f63c07d 100644
--- a/src/joyosc/GameController.cpp
+++ b/src/joyosc/GameController.cpp
@@ -87,7 +87,7 @@ bool GameController::open(void *data) {
                        printIgnores();
                }
        }
-       if(m_oscAddress == "") {
+       if(m_oscAddress == "" || m_oscAddress == "controller") {
                // not found ... set a generic name using the index
                std::stringstream stream;
                stream << "/gc" << m_indices.index;
~~~

But you surely know a better fix. :)

**Comment by agraef** [comment]
My temporary fixes are here, in case you want to pull them over: https://github.com/agraef/joyosc/tree/tmpfix

**Comment by danomatika** [comment]
Yeah, I saw the address issue earlier but didn't have time to push the fix. It's there now. I may do some more refactoring in a develop branch.

**Comment by agraef** [comment]
Looking good, thanks!

**Comment by agraef** [comment]
BTW, I've taken rev. 1af2bb115d9e3c0e7267a95f6ba645827927991a and created Mac (arm64) and Windows (x86_64) packages for my students from those now. These also include application icons which launch joyosc with the -w option required on those platforms, which should make the program easier to use for people who don't know how to run stuff from the command line.

You can find these at https://seafile.rlp.net/f/2fb67e3abb1341cf899c/ and https://seafile.rlp.net/f/d9513d9981b74aa09e9d/ if you or anyone else is interested. (I created these manually, but of course one could create a GH workflow which automates the packaging process. I'll look into that if and when I find the time.)

**Comment by agraef** [comment]
> We could wrap up package creation into per-platform scripts which are called by make, as with Pure Data.

Right. Pd has a template for the Mac app bundle in a tarball, something similar could be done for the mingw package. The only tricky part to be automatized is to figure out which Homebrew or mingw libs to include in the packages so that they're self-contained, employing otool and install_name_tool on the Mac and ldd on mingw/msys2.

My current "app bundle" for the Mac is bare-bones, though, just a shell script which launches the joyosc program. But it shouldn't be too difficult to do something more comprehensive there.

> I have made a new stable 0.7.0 release and can keep other major changes to a develop branch for now.

No need for a separate branch if you prefer working on master. As long as you tag the releases, package maintainers will be happy.
