### ISSUE TITLE
SDL window (`-w`) rendering needs SDL_WINDOWEVENT handler on Linux and Windows

### ISSUE THREAD

**Issue by agraef** [danomatika/joyosc#28]
It appears that with composite window managers on Linux at least, the window contents isn't correctly redrawn if the window is covered and then exposed again:

![image](https://github.com/user-attachments/assets/b48873c9-1107-4d46-9990-4072b79a5f2a)

This doesn't seem to happen on Mac or Windows, but on Windows the window contents isn't redrawn either when resizing the window:

![Screenshot 2024-12-15 145555](https://github.com/user-attachments/assets/cf6d8a22-538d-4433-87e1-a2bb36a76efc)

I think that in order to handle both issues, the window needs to be redrawn by handling SDL_WINDOWEVENT with event->window.event == SDL_WINDOWEVENT_SIZE_CHANGED or SDL_WINDOWEVENT_EXPOSED.

(None of this seems to happen on macOS, only Linux and Windows seem to need that event handler.)

Cf. https://stackoverflow.com/questions/44507711/how-to-correctly-refresh-sdl2-window-after-resizing

**Comment by danomatika** [comment]
This should be fixed with latest commits.

**Comment by agraef** [comment]
Yep, that fixes it. But maybe take out the debug message at App.cpp:L206:
~~~c++
LOG << "window exposed" << std::endl;
~~~

**Comment by agraef** [comment]
Thanks. All good now.
