### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by EliseoCesco** [danomatika/joyosc#8]
Good morning,
I saw this beautiful project, and I fully agree that joysticks and buttons are the most practical and economical thing for small projects.
I work with raspberry and arduino.
But I would like to make a project with windows 10, but unfortunately I can't install.
Is there an exe in the future?

Thank you

**Comment by danomatika** [comment]
I don't host binaries. You can build it with Msys2 on Windows. @fdch had success with this and may be able to provide you with his build.

**Comment by EliseoCesco** [comment]
Unfortunately with Msys2 I can't.

**Comment by danomatika** [comment]
Ok. I don't have a Windows machine myself, so I can't build a binary. Maybe you can contact @fdch as ask him about sharing the build he made.

If you do want to bud it yourself, the instructions are in the main readme.

**Comment by fdch** [comment]
> Unfortunately with Msys2 I can't.
There's a binary here: https://drive.google.com/a/nyu.edu/file/d/1txuB2RiR2Z0nhYY_cOKZNRtQY_i3nR-2/view?usp=drivesdk
Let me know if you can make it work. There are two .bat scripts to run and stop joyosc, otherwise go to the "bin" directory from the command line and run joyosc.exe
